# Generated by Django 5.1 on 2024-09-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChabotFeature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='response',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
