# Generated by Django 5.1 on 2024-09-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChabotFeature', '0002_alter_userresponse_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='session_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
